### ISSUE TITLE
Hero section

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitj-website-deploy#1053]
Navbar along with the image slider

slider shall have caption. upon clicking it shall redirect to common template page where we will fetch the description of the images and show

**Comment by AshutoshDevgotra** [comment]
ok sir, I am creating diia folder in my cloned "nitj-website-repo" , then we will commint it to this repo ryt, and tell me in public ,index.html is already present , tell me a folder structure,where i should be adding this navbar component,should i create seperate components file in public directory and work inside it and backend people can use navbar in any page directly
